### ISSUE TITLE
Front page - title text isn't the colour from the theme

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#605]
https://cdn.threesixtygiving.org/components/detail/grant-nav--default.html has the text as `rgb(21, 55, 53)` but the dev site has `rgb(0,0,0)`

**Comment by drkane** [comment]
Looks like the [grantnav style file](http://grantnav-dev.default.threesixtygiving.uk0.bigv.io/static/css/theme.css) might be missing this section: 

```css
:root {
  --colors-default: var(--color-base);
  --colors-white: #FFFFFF;
  --colors-orange: var(--color-orange);
  --colors-teal: var(--color-teal);
  --colors-yellow: var(--color-yellow);
  --colors-red: var(--color-red);
  --colors-alt: var(--colors-teal);
  --colors-black: var(--colors-default); }
```

(from https://cdn.threesixtygiving.org/components/preview/assets/css/global.css)

I might be too late with this, but I think it would be sensible if we used a CSS file that was an exact copy of the file above, and then any grantnav-specific tweaks were kept in a separate file. That way if there are updates to the global styles we can just overwrite the global file.
